### ISSUE TITLE
python-multi build missing 2.7

### ISSUE THREAD

**Issue by busunkim96** [googleapis/testing-infra-docker#106]
gcr.io/cloud-devrel-kokoro-resources/python-multi@sha256:a4d47f7e189851ae607042abcd5af8251b8a14d0a0a0316dd798abecc9d2bae2 appears to be missing Python 2.7.

This image was built on 9/22/2020 as a result of https://github.com/googleapis/testing-infra-docker/pull/103 being merged. That PR did not touch the `python-multi` Dockerfile or the cloudbuild.yaml used to update the images. Installing Python versions appear to be flaky. Investigate the logs for the build above and/or attempt to reproduce locally.

**Comment by tmatsuo** [comment]
Possibly it failed to fetch the gpg keys.

**Comment by tmatsuo** [comment]
In python-docs-samples, we use [this script](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/.kokoro/docker/fetch_gpg_keys.sh) to fetch the keys although it's still somewhat flaky.

I think the current model (having Dockerfile in this repo and the cloudbuild trigger the upload) is broken because it allows bad images being uploaded, resulting builds starting to fail in other repos.

With Trampoline V2, you can make sure the uploaded images are always correct.

**Comment by busunkim96** [comment]
@tmatsuo Would you recommend adding the Trampoline v2 bits to each client library repo? My main concern is the logistics of having the image updates coming from any library repo. 

Jeff did add a presubmit #103 so the image is built on PRs. Maybe updating the Dockerfile to fail when the key fetch fails?

**Comment by tmatsuo** [comment]
> @tmatsuo Would you recommend adding the Trampoline v2 bits to each client library repo? My main concern is the logistics of having the image updates coming from any library repo.

Probably yes. We can use the different image names for each repo so that build in a library only upload the image for that library.

> Jeff did add a presubmit #103 so the image is built on PRs. Maybe updating the Dockerfile to fail when the key fetch fails?

I don't think the presubmit prevents from uploading broken image (like missing py2.7).

**Comment by busunkim96** [comment]
The GPG key issue has been resolved.
